Revert "v0.07 incorporated Jaron's commit at rev 6527"
This reverts commit 3e2e64e9d8519988e9d77c5ba973a7c7cb53cce0.

because encountered mysterios attribute error
Traceback (most recent call last):
  File "./calc_he.py", line 155, in <module>
    pm.run_project()
  File "/home/yyang173/Software/nexus_rev6530/library/project_manager.py", line 102, in run_project
    self.progress_cascades()
  File "/home/yyang173/Software/nexus_rev6530/library/project_manager.py", line 333, in progress_cascades
    cascade.progress()
  File "/home/yyang173/Software/nexus_rev6530/library/simulation.py", line 973, in progress
    sim.progress(self.simid)
  File "/home/yyang173/Software/nexus_rev6530/library/simulation.py", line 973, in progress
    sim.progress(self.simid)
  File "/home/yyang173/Software/nexus_rev6530/library/simulation.py", line 945, in progress
    self.analyze()
  File "/home/yyang173/Software/nexus_rev6530/library/simulation.py", line 844, in analyze
    analyzer = self.analyzer_type(self)
  File "/home/yyang173/Software/nexus_rev6530/library/qmcpack_analyzer.py", line 254, in __init__
    self.init_sub_analyzers(request)
  File "/home/yyang173/Software/nexus_rev6530/library/qmcpack_analyzer.py", line 310, in init_sub_analyzers
    wavefunction = wavefunction.get_single('psi0')
AttributeError: 'str' object has no attribute 'get_single'